#!/usr/bin/env php
<?php
define('ENVIRONMENT', 'cli');
set_time_limit(0);

$app = require_once dirname(__DIR__) ."/app/bootstrap.php";

$console = $app["console"];
Doctrine\ORM\Tools\Console\ConsoleRunner::addCommands($console);
$console->run();