<?php

namespace Model;

/**
 * LanguageLevelRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageLevelRepo extends \Doctrine\ORM\EntityRepository
{
}
